<a href="https://colab.research.google.com/github/Ravikumar10593-hub/15daybootcamp-day-1/blob/main/Day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
import numpy as np


In [ ]:
a=[1,2,3,4]
arr1=np.array(a)
print(a)
print(type(arr1))

[1, 2, 3, 4]
<class 'numpy.ndarray'>


**Showing why numpy is better than list**

In [ ]:
import sys
s=range(1000)
print("size of each byte",sys.getsizeof(s))
print("size of full list",sys.getsizeof(s)*len(s))

size of each byte 48
size of full list 48000


In [ ]:
#doing same thing in numpy
import numpy as np
x=np.arange(1000)
print("Size of each element",x.itemsize)
print("Size of whole list",x.size * x.itemsize)


Size of each element 8
Size of whole list 8000


In [ ]:
import time
a=range(1000)
b=range(1000)
start= time.time()
#string comprehension
ab=[a*b for a,b in zip(a,b)]
end=time.time()
print("total time: ",end-start)

total time:  0.0001583099365234375


In [ ]:
import time
import numpy as np
arr1=np.arange(1000)
arr2=np.arange(1000)
start= time.time()
m=arr1 *arr2
end=time.time()
print("total time: ",end-start)

total time:  7.581710815429688e-05


In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]],ndmin=2)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
arr1=np.zeros((2,2))
print(arr1)

[[0. 0.]
 [0. 0.]]


In [3]:
#creating n dim array

In [6]:
a=[[1,2,3],[4,5,6]]
np.array(a,ndmin=2)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.random.rand(3,2)

array([[0.56995343, 0.10395693],
       [0.6445781 , 0.43585846],
       [0.94650253, 0.92203965]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
arr1=np.random.rand(3,2)
arr2=np.random.rand(3,2)
sum1=np.add(arr1,arr2)
sub1=np.subtract(arr1,arr2)
print(arr1)
print(arr2)
print(sum1)
print(sub1)

[[0.04559147 0.43986746]
 [0.9599082  0.90470988]
 [0.60790558 0.81885654]]
[[0.03296531 0.34539524]
 [0.24303341 0.28822416]
 [0.36406288 0.31831639]]
[[0.07855678 0.78526269]
 [1.20294161 1.19293404]
 [0.97196846 1.13717293]]
[[0.01262616 0.09447222]
 [0.71687479 0.61648573]
 [0.2438427  0.50054016]]


#indexing and slicing

In [20]:
a=[1,2,3,"ravi"]

In [21]:
a[-1]

'ravi'

In [22]:
a[:-1]

[1, 2, 3]

In [23]:
a[-3:-1]

[2, 3]

In [24]:
a[0::2] #skipped the value by one

[1, 3]

In [28]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1
arr2=arr1
arr2.reshape(1,6)
arr2

array([[1, 2, 3],
       [4, 5, 6]])